version: '3'
services:
  discord-text2speech:
    restart: always
    container_name: discord-text2speech
    build: .
    image: yude/discord-text2speech
    environment:
    # Discord bot token
    - TOKEN=